"""Windows 部署：任务计划程序每分钟跑一次 run-once（等价 launchd StartInterval=60），
托盘脚本写入当前用户 Run 键登录自启。全部用户级操作，不需要管理员。

原生 Windows 只支持 API 渠道（OpenAI / Anthropic 协议）：没有 sandbox-exec 或 Docker 隔离，
不在宿主上直接运行模型 CLI。打包的 WorldQuantTray.exe 自带引擎，调度与自启都指向 exe 本身。"""
import argparse
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys

TASK = 'WorldQuantWQRunner'
RUN_KEY = r'HKCU\Software\Microsoft\Windows\CurrentVersion\Run'
TRAY_VALUE = 'WorldQuantTray'


def _t(zh, en):
    try:
        from .i18n import default_language, text
    except ImportError:                      # 被 scripts/ 以文件方式加载时无包上下文
        from wq.i18n import default_language, text
    return text(default_language(), zh, en)


def frozen():
    return bool(getattr(sys, 'frozen', False))


def render(root, runtime):
    """生成默认关闭的 Windows 配置：只放 API 渠道由向导写入，不生成 CLI 启动器。"""
    from .assets import path as asset_path
    root = Path(root).resolve(); runtime = Path(runtime).expanduser().resolve()
    if runtime.is_relative_to(root) or root.is_relative_to(runtime):
        raise ValueError('Runtime and project must be separate directories')
    targets = [root / 'config' / n for n in ('config.json', 'profiles.json', 'autopilot-policy.json')]
    if runtime.exists() or any(p.exists() for p in targets):
        raise ValueError('Refusing to overwrite existing deployment')
    jobs = runtime / 'jobs'
    jobs.mkdir(parents=True)
    cfg = json.loads(asset_path('config.example.json').read_text(encoding='utf-8'))
    cfg['routing']['work_root'] = str(jobs)
    profiles = json.loads(asset_path('profiles.example.json').read_text(encoding='utf-8'))
    profiles['providers'] = {}
    (root / 'config').mkdir(parents=True, exist_ok=True)
    for path, data in [(targets[0], cfg), (targets[1], profiles)]:
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    targets[2].write_text(asset_path('autopilot-policy.example.json').read_text(encoding='utf-8'), encoding='utf-8')
    return runtime


def pythonw_exe(python):
    """优先用 pythonw.exe（无控制台窗口）；找不到就退回原解释器。"""
    guess = Path(python).with_name('pythonw.exe')
    return str(guess) if guess.exists() else str(python)


def validate(root, python):
    if any(c in str(root) + str(python) for c in ('\n', '\r', '"')):
        raise ValueError('路径不能包含换行或双引号')


def wrapper_script(root):
    """每分钟被任务计划程序启动一次：进入项目根、日志落 var/run、跑一个 run-once。"""
    return f'''# -*- coding: utf-8 -*-
# Generated by wq.windows_setup — do not edit.
import os, sys
ROOT = {str(root)!r}
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, 'src'))
def _log(name):
    return open(os.path.join(ROOT, 'var', 'run', name), 'a', buffering=1, encoding='utf-8')
sys.stdout = _log('runner.out.log')
sys.stderr = _log('runner.err.log')
from wq import cli
raise SystemExit(cli.main(['run-once', '--lease', '3600']))
'''


def runner_task_args(root, python):
    if frozen():
        # exe 自带引擎：--scheduled-run 把输出写进 var/run 日志后跑一次 run-once。
        tr = f'"{python}" --workspace "{Path(root)}" --scheduled-run'
    else:
        tr = f'"{pythonw_exe(python)}" "{Path(root) / "var" / "run" / "wq_runner.pyw"}"'
    return ['schtasks', '/Create', '/TN', TASK, '/TR', tr, '/SC', 'MINUTE', '/MO', '1', '/F']


def tray_run_value(root, python):
    if frozen():
        return f'"{python}" --workspace "{Path(root)}"'
    return f'"{pythonw_exe(python)}" "{Path(root) / "scripts" / "desktop_tray.py"}"'


def register_runner(root, python=None):
    """注册（或覆盖）每分钟一次的调度任务；幂等。"""
    python = python or sys.executable
    root = Path(root).resolve()
    validate(root, python)
    run_dir = root / 'var' / 'run'
    run_dir.mkdir(parents=True, exist_ok=True)
    if not frozen():
        (run_dir / 'wq_runner.pyw').write_text(wrapper_script(root), encoding='utf-8')
    result = subprocess.run(runner_task_args(root, python), capture_output=True, text=True, errors='replace')
    if result.returncode:
        raise RuntimeError((result.stderr or result.stdout or f'schtasks exit {result.returncode}')[-500:])
    return run_dir


def _importable(module):
    try:
        return importlib.util.find_spec(module) is not None
    except ImportError:
        return False


def main(argv=None):
    parser = argparse.ArgumentParser(description='注册/移除 Windows 调度与托盘自启')
    parser.add_argument('--root', default=os.getcwd())
    parser.add_argument('--python', default=sys.executable)
    parser.add_argument('--remove', action='store_true', help='移除调度任务与自启；不动队列与账本')
    parser.add_argument('--no-tray', action='store_true', help='只注册调度，不设托盘登录自启（纯命令行 / AI 使用）')
    args = parser.parse_args(argv)
    if sys.platform != 'win32':
        raise SystemExit(_t('此脚本仅用于 Windows；macOS 用 scripts/install_menubar.py，Linux 用 scripts/setup_linux.py',
                            'Windows only; use scripts/install_menubar.py on macOS and scripts/setup_linux.py on Linux.'))
    root = Path(args.root).resolve()
    validate(root, args.python)
    if args.remove:
        subprocess.run(['schtasks', '/Delete', '/TN', TASK, '/F'], check=False)
        subprocess.run(['reg', 'delete', RUN_KEY, '/v', TRAY_VALUE, '/f'], check=False)
        print(_t('已移除：调度任务与托盘自启；研究队列与账本保持原状',
                'Removed: the scheduler task and tray auto-start; the research queue and ledger are unchanged.'))
        return 0
    run_dir = register_runner(root, args.python)
    if args.no_tray:
        print(_t(f'已注册调度任务 {TASK}（每分钟一次）；未设托盘自启。日志在 {run_dir}',
                 f'Registered scheduler task {TASK} (every minute); tray auto-start not set. Logs in {run_dir}'))
        return 0
    subprocess.run(['reg', 'add', RUN_KEY, '/v', TRAY_VALUE, '/t', 'REG_SZ',
                    '/d', tray_run_value(root, args.python), '/f'], check=True)
    print(_t(f'已注册调度任务 {TASK}（每分钟一次）与托盘登录自启；日志在 {run_dir}',
             f'Registered scheduler task {TASK} (every minute) and tray auto-start; logs in {run_dir}'))
    if frozen():
        print(_t('托盘登录自启已设置；下次登录自动打开', 'Tray auto-start set; it opens at next sign-in'))
        return 0
    missing = [m for m in ('pystray', 'PIL') if not _importable(m)]
    if missing:
        print(_t(f'缺少托盘依赖 {", ".join(missing)}；请先运行 {args.python} -m pip install pystray Pillow，'
                   f'然后运行 {pythonw_exe(args.python)} scripts\\desktop_tray.py',
                 f'Missing tray dependencies {", ".join(missing)}; run {args.python} -m pip install pystray Pillow first, '
                 f'then {pythonw_exe(args.python)} scripts\\desktop_tray.py'))
        return 0
    subprocess.Popen([pythonw_exe(args.python), str(root / 'scripts' / 'desktop_tray.py')],
                     cwd=str(root), close_fds=True)
    print(_t('托盘已启动', 'Tray started'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
