"""Windows 部署：任务计划程序每分钟跑一次 run-once（等价 launchd StartInterval=60），
托盘脚本写入当前用户 Run 键登录自启。全部用户级操作，不需要管理员。"""
import argparse
import importlib.util
import os
from pathlib import Path
import subprocess
import sys

TASK = 'WorldQuantWQRunner'
RUN_KEY = r'HKCU\Software\Microsoft\Windows\CurrentVersion\Run'
TRAY_VALUE = 'WorldQuantTray'


def pythonw_exe(python):
    """优先用 pythonw.exe（无控制台窗口）；找不到就退回原解释器。"""
    guess = Path(python).with_name('pythonw.exe')
    return str(guess) if guess.exists() else str(python)


def validate(root, python):
    if any(c in str(root) + str(python) for c in ('\n', '\r', '"')):
        raise ValueError('路径不能包含换行或双引号')


def wrapper_script(root):
    """每分钟被任务计划程序启动一次：进入项目根、日志落 var/run、跑一个 run-once。"""
    return f'''# -*- coding: utf-8 -*-
# Generated by wq.windows_setup — do not edit.
import os, sys
ROOT = {str(root)!r}
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, 'src'))
def _log(name):
    return open(os.path.join(ROOT, 'var', 'run', name), 'a', buffering=1, encoding='utf-8')
sys.stdout = _log('runner.out.log')
sys.stderr = _log('runner.err.log')
from wq import cli
raise SystemExit(cli.main(['run-once', '--lease', '3600']))
'''


def runner_task_args(root, python):
    pyw = pythonw_exe(python)
    return ['schtasks', '/Create', '/TN', TASK,
            '/TR', f'"{pyw}" "{Path(root) / "var" / "run" / "wq_runner.pyw"}"',
            '/SC', 'MINUTE', '/MO', '1', '/F']


def tray_run_value(root, python):
    return f'"{pythonw_exe(python)}" "{Path(root) / "scripts" / "desktop_tray.py"}"'


def _importable(module):
    try:
        return importlib.util.find_spec(module) is not None
    except ImportError:
        return False


def main(argv=None):
    parser = argparse.ArgumentParser(description='注册/移除 Windows 调度与托盘自启')
    parser.add_argument('--root', default=os.getcwd())
    parser.add_argument('--python', default=sys.executable)
    parser.add_argument('--remove', action='store_true', help='移除调度任务与自启；不动队列与账本')
    args = parser.parse_args(argv)
    if sys.platform != 'win32':
        raise SystemExit('此脚本仅用于 Windows；macOS 用 scripts/install_menubar.py，Linux 用 scripts/setup_linux.py')
    root = Path(args.root).resolve()
    validate(root, args.python)
    if args.remove:
        subprocess.run(['schtasks', '/Delete', '/TN', TASK, '/F'], check=False)
        subprocess.run(['reg', 'delete', RUN_KEY, '/v', TRAY_VALUE, '/f'], check=False)
        print('已移除：调度任务与托盘自启；研究队列与账本保持原状')
        return 0
    run_dir = root / 'var' / 'run'
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / 'wq_runner.pyw').write_text(wrapper_script(root), encoding='utf-8')
    subprocess.run(runner_task_args(root, args.python), check=True)
    subprocess.run(['reg', 'add', RUN_KEY, '/v', TRAY_VALUE, '/t', 'REG_SZ',
                    '/d', tray_run_value(root, args.python), '/f'], check=True)
    print(f'已注册调度任务 {TASK}（每分钟一次）与托盘登录自启；日志在 {run_dir}')
    missing = [m for m in ('pystray', 'PIL') if not _importable(m)]
    if missing:
        print(f'缺少托盘依赖 {", ".join(missing)}；请先运行 {args.python} -m pip install pystray Pillow，'
              f'然后运行 {pythonw_exe(args.python)} scripts\\desktop_tray.py')
        return 0
    subprocess.Popen([pythonw_exe(args.python), str(root / 'scripts' / 'desktop_tray.py')],
                     cwd=str(root), close_fds=True)
    print('托盘已启动')
    return 0


if __name__ == '__main__':
    sys.exit(main())
